[package]
name = "sched-client-seed"
version = "0.1.0"
authors = ["Jeff Wright <jeffw387@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
seed = "^0.3"
wasm-bindgen = "^0.2.38"
web-sys = "^0.3.15"
